name: 'Build and test app'

on:
  push:
    branches:
      - playwright-e2e-tests
  pull_request:
    branches:
      - main
      - dev

env:
  NODE_VERSION: 21.6.1
  PHP_VERSION: 8.3

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: 'Install composer dependencies'
        run: composer install

      - name: 'Install npm dependencies'
        run: npm ci

      - name: 'Build frontend'
        run: npm run build

      - name: 'Create .env file'
        run: cp .env.ci .env

      - name: 'Generate laravel app key'
        run: php artisan key:generate

      - name: 'Install octane'
        run: php artisan octane:install --no-interaction --server=roadrunner

      - name: Archive installation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installation_artifacts
          path: |
            ./

  e2e_tests:
    name: e2e_tests
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mmbd
        ports:
          - 3306:3306

    steps:
      - uses: actions/download-artifact@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Move artifact files to current dir
        run: mv installation_artifacts/{*,.[^.]*} ./ && rm -r installation_artifacts

      - name: Make files executable
        run: find . -type f -iname "**/+(playwright)" -exec chmod +x {} \;

      - name: Display structure of downloaded files
        run: ls -alh

      - name: 'Migrate database'
        run: php artisan migrate --seed

      - name: 'Generate playwright test users'
        run: php artisan playwright:create-users

      - name: 'Start octane server'
        run: php artisan octane:start > /dev/null &

      - name: 'Start inertia SSR Server'
        run: php artisan inertia:start-ssr > /dev/null &

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  php_test:
    name: php_test
    needs: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mmbd
        ports:
          - 3306:3306

    steps:
      - uses: actions/download-artifact@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Move artifact files to current dir
        run: mv installation_artifacts/{*,.[^.]*} ./ && rm -r installation_artifacts

      - name: 'Start inertia SSR Server'
        run: php artisan inertia:start-ssr > /dev/null &

      - name: 'Execute tests'
        id: tests
        run: php artisan test -p

      - name: 'Execute tests serially if parallel tests fail'
        if: failure() && steps.tests.outcome == 'failure'
        run: php artisan test