name: 'Build and test app'

on:
  pull_request:
    branches:
      - main
      - dev

env:
  NODE_VERSION: 21.6.1
  PHP_VERSION: 8.3

jobs:

  e2e_tests:
    name: e2e_tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mmbd
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Install playwright
        run: npx playwright install --with-deps

      - name: 'Migrate database'
        run: php artisan migrate --seed

      - name: 'Generate playwright test users'
        run: php artisan playwright:create-users

      - name: 'Start octane server'
        run: php artisan octane:start > /dev/null &

      - name: 'Start inertia SSR Server'
        run: php artisan inertia:start-ssr > /dev/null &

      - name: Run Playwright tests
        run: npx playwright test
        env:
          APP_URL: 'http://127.0.0.1:8000'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  php_test:
    name: php_test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mmbd
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: 'Start inertia SSR Server'
        run: php artisan inertia:start-ssr > /dev/null &

      - name: 'Execute tests'
        id: tests
        run: php artisan test -p

      - name: 'Execute tests serially if parallel tests fail'
        if: failure() && steps.tests.outcome == 'failure'
        run: php artisan test